# Generated by Django 3.2 on 2021-05-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('services', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('typeOfCar', models.CharField(choices=[('Used', 'Used'), ('New', 'New')], default='Used', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speciality', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speciality', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpareImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('spare', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate.spare')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('mechanic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='CarSaleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('carSale', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate.carsale')),
            ],
        ),
        migrations.CreateModel(
            name='AutoDiagnosticImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/')),
                ('image', models.ImageField(upload_to='media/')),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('mechanic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliate.autodiagnostic')),
            ],
        ),
    ]
