# Generated by Django 3.2 on 2021-08-20 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_auto_20210602_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autodiagnosticimage',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='carsaleimage',
            name='carSale',
        ),
        migrations.RemoveField(
            model_name='mechanicimage',
            name='mechanic',
        ),
        migrations.RemoveField(
            model_name='spareimage',
            name='spare',
        ),
        migrations.DeleteModel(
            name='AutoDiagnostic',
        ),
        migrations.DeleteModel(
            name='AutoDiagnosticImage',
        ),
        migrations.DeleteModel(
            name='CarSale',
        ),
        migrations.DeleteModel(
            name='CarSaleImage',
        ),
        migrations.DeleteModel(
            name='Mechanic',
        ),
        migrations.DeleteModel(
            name='MechanicImage',
        ),
        migrations.DeleteModel(
            name='Spare',
        ),
        migrations.DeleteModel(
            name='SpareImage',
        ),
    ]
