# Generated by Django 3.2 on 2021-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('merch_type', models.CharField(choices=[('Tees', 'Tees'), ('Shorts', 'Shorts'), ('Sweat-Shirt', 'Sweat-Shirt'), ('Hoodie', 'Hoodie'), ('Face cap', 'Face cap'), ('Knapsack', 'Knapsack'), ('Socks', 'Socks')], default='', max_length=200)),
                ('merch_size', models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra-Large'), ('XXL', 'XXtra-Large')], default='', max_length=200)),
                ('in_box', models.CharField(max_length=255)),
            ],
        ),
    ]
