# Generated by Django 3.2 on 2021-05-15 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20210515_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('new_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('merch_type', models.CharField(choices=[('Tees', 'Tees'), ('Shorts', 'Shorts'), ('Sweat-Shirt', 'Sweat-Shirt'), ('Hoodie', 'Hoodie'), ('Face cap', 'Face cap'), ('Knapsack', 'Knapsack'), ('Socks', 'Socks')], default='', max_length=200)),
                ('merch_size', models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('XL', 'Xtra-Large'), ('XXL', 'XXtra-Large')], default='', max_length=200)),
                ('in_box', models.CharField(max_length=255)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='Store.imagealbum')),
            ],
        ),
        migrations.DeleteModel(
            name='Merch',
        ),
    ]
