# Generated by Django 3.2 on 2021-05-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20210515_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='album',
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Store.merchandise'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
