# Generated by Django 3.2 on 2021-05-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('faults', models.TextField(blank=True)),
                ('make', models.CharField(max_length=200)),
                ('man_year', models.DateField()),
                ('registered', models.BooleanField(default=False)),
                ('distance_covered', models.IntegerField()),
                ('gear', models.CharField(max_length=10)),
                ('transmission', models.CharField(choices=[('AUTO', 'Authomatic'), ('MANUAL', 'Manual')], max_length=200)),
                ('usage_type', models.CharField(choices=[('UK', 'UK-Used'), ('US', 'US-Used'), ('NIG', 'Nigerian-Used'), ('Other', 'Other')], default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('Ife', 'Ile-Ife'), ('Ibadan', 'Ibadan'), ('Lagos', 'Lagos')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AutoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Store.auto')),
            ],
        ),
        migrations.CreateModel(
            name='MerchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('default', models.BooleanField(default=False)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='merchandise',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='location',
            field=models.CharField(choices=[('Ife', 'Ile-Ife'), ('Ibadan', 'Ibadan'), ('Lagos', 'Lagos')], default='Ife', max_length=200),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='merchimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Store.merchandise'),
        ),
    ]
