# Generated by Django 3.2 on 2021-05-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20210515_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoimage',
            name='default',
        ),
        migrations.RemoveField(
            model_name='merchimage',
            name='default',
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Store.auto'),
        ),
        migrations.AlterField(
            model_name='merchimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Store.merchandise'),
        ),
    ]
