# Generated by Django 3.2 on 2021-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20210519_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimage',
            name='video',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
