# Generated by Django 3.2 on 2021-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_autoimage_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimage',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='video',
            field=models.FileField(blank=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='merchimage',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
