# Generated by Django 3.2 on 2021-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_auto_20210602_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='color_variation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
