# Generated by Django 3.2 on 2021-07-10 02:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_merchandise_color_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='autoimage',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='merchimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
