# Generated by Django 3.2 on 2021-05-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_eventimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventImg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='EventImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
