# Generated by Django 3.2 on 2021-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_remove_event_eventimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimg',
            name='video',
            field=models.FileField(default='', upload_to='static/media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimg',
            name='image',
            field=models.FileField(upload_to='static/media/'),
        ),
    ]
