# Generated by Django 3.2 on 2021-06-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_auto_20210602_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimg',
            name='video',
            field=models.FileField(null=True, upload_to='static/media/'),
        ),
    ]
