# Generated by Django 3.2 on 2021-07-21 06:15

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0008_auto_20210710_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimg',
            name='video',
        ),
        migrations.CreateModel(
            name='EventVid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='video')),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
