# Generated by Django 3.2 on 2021-07-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0011_alter_eventvid_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvid',
            name='video',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
