# Generated by Django 3.2 on 2021-08-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0013_auto_20210726_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('Past', 'Past'), ('Upcoming', 'Upcoming')], default='U', max_length=10),
        ),
    ]
