# Generated by Django 3.2 on 2021-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsale',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
