# Generated by Django 3.2 on 2021-08-10 08:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0002_alter_carsale_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsale',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
