# Generated by Django 3.2 on 2021-08-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0003_alter_carsale_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsale',
            name='video',
        ),
    ]
