# Generated by Django 3.2 on 2021-08-10 09:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0004_remove_carsale_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsale',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
