# Generated by Django 3.2 on 2021-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0005_carsale_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
