# Generated by Django 3.2 on 2021-08-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0006_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect', models.BooleanField(default=False)),
                ('person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Automart.inspection')),
            ],
        ),
    ]
