# Generated by Django 3.2 on 2021-08-18 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Automart', '0008_inspection_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='car',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_inspection', to='Automart.carsale'),
        ),
    ]
