# Generated by Django 3.2 on 2021-07-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_cartitem_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total',
            new_name='price',
        ),
    ]
