# Generated by Django 3.2 on 2021-07-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_rename_total_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
