# Generated by Django 3.2 on 2021-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_cart_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
