# Generated by Django 3.2 on 2021-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0008_cartitem_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery',
            field=models.CharField(default='', max_length=500),
        ),
    ]
