# Generated by Django 3.2 on 2021-07-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_cartitem_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery',
        ),
    ]
