# Generated by Django 3.2 on 2021-07-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cart', '0010_remove_cartitem_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='trans_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=30)),
                ('trans_id', models.CharField(default='', max_length=300)),
                ('failure', models.BooleanField(default=True)),
                ('error', models.CharField(max_length=1000)),
                ('message_body', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
