# Generated by Django 3.2 on 2021-07-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_auto_20210723_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='error',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_body',
            field=models.TextField(),
        ),
    ]
