# Generated by Django 3.2 on 2021-07-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_auto_20210723_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='trans_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
