# Generated by Django 3.2 on 2021-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0013_alter_cart_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='trans_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
