# Generated by Django 3.2 on 2021-06-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='login',
        ),
    ]
