# Generated by Django 3.2 on 2021-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
